Unconditionally require gio-2.0, gio-unix-2.0
Fixes the following on NixOS:

pulseaudio-mpris-player.c:25:10: fatal error: gio/gdesktopappinfo.h: No such file or directory
   25 | #include <gio/gdesktopappinfo.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

The reason here is the same as https://gitlab.xfce.org/xfce/xfce4-session/-/merge_requests/51.

It looks like the associated code paths are built unconditionally.